name: dart_3des
description: Triple DES and DES block cipher implementation ported from CryptoJS
version: 1.0.0
homepage: https://github.com/juniorkibirige/tripledes-dart
# author: Junior Lawrence Kibirige <junior.kibirige@students.mak.ac.ug>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
